#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def get_sum(arr, m, n):
    sum_ = 0
    sum_ += (arr[m-1][n-1] + arr[m-1][n] + arr[m-1][n+1])
    sum_ += arr[m][n]
    sum_ += (arr[m+1][n-1] + arr[m+1][n] + arr[m+1][n+1])
    return sum_


def hourglassSum(arr):
    ans = -63
    for i in range(1, 5):
        for j in range(1, 5):
            current_sum = get_sum(arr, i, j)
            if current_sum > ans:
                ans = current_sum
    return ans


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
